# Generated by Django 3.1 on 2022-04-27 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ('user', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Высота')),
                ('width', models.PositiveSmallIntegerField(verbose_name='Ширина')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('image',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='имя тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo_albums.album', verbose_name='Альбом')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photo_albums.image', verbose_name='Изображение')),
                ('tags', models.ManyToManyField(blank=True, related_name='photos', to='photo_albums.Tag', verbose_name='Теги')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('user', 'album', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ImageSmall',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photo_albums.image')),
                ('image_original', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='small', to='photo_albums.image', verbose_name='Оригинал изображение')),
            ],
            options={
                'verbose_name': 'Миниатюра Изображения',
                'verbose_name_plural': 'Миниатюры Изображений',
                'ordering': ('image', 'image_original'),
            },
            bases=('photo_albums.image',),
        ),
    ]
