# Generated by Django 3.1 on 2022-04-29 09:33

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('photo_albums', '0002_auto_20220428_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение'),
        ),
    ]
