# Generated by Django 3.1 on 2022-04-29 09:39

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('photo_albums', '0003_auto_20220429_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение_m'),
        ),
    ]
